# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import ActionImageMediaStream_pb2 as grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2



class VoiceAgentStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamSession = channel.stream_stream(
                '/robotic.voice.VoiceAgent/StreamSession',
                request_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioRequest.SerializeToString,
                response_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioResponse.FromString,
                _registered_method=True)
        self.ProcessAudioUnary = channel.unary_unary(
                '/robotic.voice.VoiceAgent/ProcessAudioUnary',
                request_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioUnaryRequest.SerializeToString,
                response_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioUnaryResponse.FromString,
                _registered_method=True)
        self.SetModelPreference = channel.unary_unary(
                '/robotic.voice.VoiceAgent/SetModelPreference',
                request_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ModelPreferenceRequest.SerializeToString,
                response_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ModelPreferenceResponse.FromString,
                _registered_method=True)
        self.UploadImage = channel.unary_unary(
                '/robotic.voice.VoiceAgent/UploadImage',
                request_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ImageUploadRequest.SerializeToString,
                response_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ImageUploadResponse.FromString,
                _registered_method=True)


class VoiceAgentServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamSession(self, request_iterator, context):
        """双向流：客户端发送音频分片，服务端返回音频分片（TTS）/文本/事件
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ProcessAudioUnary(self, request, context):
        """也提供一个简单的 unary RPC 供短语或离线任务使用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SetModelPreference(self, request, context):
        """端侧声明/更新会话希望使用的LLM模型与可选的推理参数
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UploadImage(self, request, context):
        """上传图片接口，供后续多模态理解、对话使用
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VoiceAgentServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamSession': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamSession,
                    request_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioRequest.FromString,
                    response_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioResponse.SerializeToString,
            ),
            'ProcessAudioUnary': grpc.unary_unary_rpc_method_handler(
                    servicer.ProcessAudioUnary,
                    request_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioUnaryRequest.FromString,
                    response_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioUnaryResponse.SerializeToString,
            ),
            'SetModelPreference': grpc.unary_unary_rpc_method_handler(
                    servicer.SetModelPreference,
                    request_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ModelPreferenceRequest.FromString,
                    response_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ModelPreferenceResponse.SerializeToString,
            ),
            'UploadImage': grpc.unary_unary_rpc_method_handler(
                    servicer.UploadImage,
                    request_deserializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ImageUploadRequest.FromString,
                    response_serializer=grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ImageUploadResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'robotic.voice.VoiceAgent', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('robotic.voice.VoiceAgent', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VoiceAgent(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamSession(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/robotic.voice.VoiceAgent/StreamSession',
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioRequest.SerializeToString,
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ProcessAudioUnary(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotic.voice.VoiceAgent/ProcessAudioUnary',
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioUnaryRequest.SerializeToString,
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.AudioUnaryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SetModelPreference(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotic.voice.VoiceAgent/SetModelPreference',
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ModelPreferenceRequest.SerializeToString,
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ModelPreferenceResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UploadImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/robotic.voice.VoiceAgent/UploadImage',
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ImageUploadRequest.SerializeToString,
            grpc__layer_dot_protos_dot_ActionImageMediaStream__pb2.ImageUploadResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
